#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Sep 03 16:18:13 2009
from wx._core import EVT_BUTTON

import wx

# begin wxGlade: extracode
# end wxGlade

colorArray = ['BLACK', 'GREEN', 'BROWN', 'PURPLE', 'RED', 'WHITE', 'BLUE', 'YELLOW', ]

ID_B9 = 9
ID_B10 = 10
ID_B11 = 11
ID_B12 = 12
ID_B13 = 13
ID_B14 = 14
ID_B15 = 15
ID_B16 = 16
ID_B17 = 17
ID_B18 = 18
ID_B19 = 19
ID_B20 = 20
ID_B21 = 21
ID_B22 = 22
ID_B23 = 23
ID_B24 = 24
ID_B25 = 25
ID_B26 = 26
ID_B27 = 27
ID_B28 = 28
ID_B29 = 29
ID_B30 = 30
ID_B31 = 31
ID_B32 = 32
ID_B33 = 33



class MyFrame2(wx.Frame):
    
    b_9Count = 0
    b_10Count = 0
    b_11Count = 0
    b_12Count = 0
    b_13Count = 0
    b_14Count = 0
    b_15Count = 0
    b_16Count = 0
    b_17Count = 0
    b_18Count = 0
    b_19Count = 0
    b_20Count = 0
    b_21Count = 0
    b_22Count = 0
    b_23Count = 0
    b_24Count = 0
    b_25Count = 0
    b_26Count = 0
    b_27Count = 0
    b_28Count = 0
    b_29Count = 0
    b_30Count = 0
    b_31Count = 0
    b_32Count = 0
    b_33Count = 0
    
       
    def increase(self, clickCount):
        if clickCount == 7:
            self.b_15Count = 0
        else:
            self.b_15Count = self.b_15Count + 1
    
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        #Panels
        self.panel_1 = wx.Panel(self, -1)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_3 = wx.Panel(self, -1)
        self.panel_4 = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self, -1)
        self.panel_6 = wx.Panel(self, -1)
        
        #Labels
        self.label_2 = wx.StaticText(self, -1, "label_2")
        self.label_3 = wx.StaticText(self, -1, "label_3")
        self.label_4 = wx.StaticText(self, -1, "label_4")
        self.label_5 = wx.StaticText(self, -1, "label_5")
        self.label_6 = wx.StaticText(self, -1, "label_6")
        self.label_7 = wx.StaticText(self, -1, "label_7")
        self.label_8 = wx.StaticText(self, -1, "label_8")
        self.label_9 = wx.StaticText(self, -1, "label_9")
        self.label_12 = wx.StaticText(self, -1, "label_12")
        self.label_13 = wx.StaticText(self, -1, "label_13")
        self.label_14 = wx.StaticText(self, -1, "label_14")
        self.label_15 = wx.StaticText(self, -1, "label_15")
        self.label_17 = wx.StaticText(self, -1, "label_17")
        self.label_10 = wx.StaticText(self, -1, "label_10")
        self.label_11 = wx.StaticText(self, -1, "label_11")
        self.label_1 = wx.StaticText(self, -1, "label_1")
        self.label_16 = wx.StaticText(self, -1, "label_16")
        
        #Buttons
        self.button_9 = wx.Button(self, ID_B9, "")
        self.button_10 = wx.Button(self, ID_B10, "")
        self.button_11 = wx.Button(self, ID_B11, "")
        self.button_12 = wx.Button(self, ID_B12, "")
        self.button_13 = wx.Button(self, ID_B13, "")
        self.button_14 = wx.Button(self, ID_B14, "")
        self.button_15 = wx.Button(self, ID_B15, "")
        self.button_16 = wx.Button(self, ID_B16, "")        
        self.button_17 = wx.Button(self, ID_B17, "")
        self.button_18 = wx.Button(self, ID_B18, "")
        self.button_19 = wx.Button(self, ID_B19, "")
        self.button_20 = wx.Button(self, ID_B20, "")       
        self.button_21 = wx.Button(self, ID_B21, "")
        self.button_22 = wx.Button(self, ID_B22, "")
        self.button_23 = wx.Button(self, ID_B23, "")
        self.button_24 = wx.Button(self, ID_B24, "")       
        self.button_25 = wx.Button(self, ID_B25, "")
        self.button_26 = wx.Button(self, ID_B26, "")       
        self.button_27 = wx.Button(self, ID_B27, "")
        self.button_28 = wx.Button(self, ID_B28, "")       
        self.button_29 = wx.Button(self, ID_B29, "")
        self.button_30 = wx.Button(self, ID_B30, "")
        self.button_31 = wx.Button(self, ID_B31, "")
        self.button_32 = wx.Button(self, ID_B32, "")
        self.button_33 = wx.Button(self, ID_B33, "")
        
        # Button Binder
        self.Bind(wx.EVT_BUTTON, self.b9Click, id=ID_B9)
        self.Bind(wx.EVT_BUTTON, self.b10Click, id=ID_B10) 
        self.Bind(wx.EVT_BUTTON, self.b11Click, id=ID_B11) 
        self.Bind(wx.EVT_BUTTON, self.b12Click, id=ID_B12) 
        self.Bind(wx.EVT_BUTTON, self.b13Click, id=ID_B13) 
        self.Bind(wx.EVT_BUTTON, self.b14Click, id=ID_B14) 
        self.Bind(wx.EVT_BUTTON, self.b15Click, id=ID_B15) 
        self.Bind(wx.EVT_BUTTON, self.b16Click, id=ID_B16) 
        self.Bind(wx.EVT_BUTTON, self.b17Click, id=ID_B17) 
        self.Bind(wx.EVT_BUTTON, self.b18Click, id=ID_B18) 
        self.Bind(wx.EVT_BUTTON, self.b19Click, id=ID_B19) 
        self.Bind(wx.EVT_BUTTON, self.b20Click, id=ID_B20) 
        self.Bind(wx.EVT_BUTTON, self.b21Click, id=ID_B21) 
        self.Bind(wx.EVT_BUTTON, self.b22Click, id=ID_B22) 
        self.Bind(wx.EVT_BUTTON, self.b23Click, id=ID_B23) 
        self.Bind(wx.EVT_BUTTON, self.b24Click, id=ID_B24) 
        self.Bind(wx.EVT_BUTTON, self.b25Click, id=ID_B25) 
        self.Bind(wx.EVT_BUTTON, self.b26Click, id=ID_B26) 
        self.Bind(wx.EVT_BUTTON, self.b27Click, id=ID_B27) 
        self.Bind(wx.EVT_BUTTON, self.b28Click, id=ID_B28) 
        self.Bind(wx.EVT_BUTTON, self.b29Click, id=ID_B29) 
        self.Bind(wx.EVT_BUTTON, self.b30Click, id=ID_B30) 
        self.Bind(wx.EVT_BUTTON, self.b31Click, id=ID_B31) 
        self.Bind(wx.EVT_BUTTON, self.b32Click, id=ID_B32) 
        self.Bind(wx.EVT_BUTTON, self.b33Click, id=ID_B33) 
 

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
    def b9Click(self, event):
        self.button_9.SetBackgroundColour(colorArray[self.b_9Count])
        self.increase(self.b_9Count)
    
    def b10Click(self, event):
        self.button_10.SetBackgroundColour(colorArray[self.b_10Count])
        self.increase(self.b_10Count)
        
    def b11Click(self, event):
        self.button_11.SetBackgroundColour(colorArray[self.b_11Count])
        self.increase(self.b_11Count)
        
    def b12Click(self, event):
        self.button_12.SetBackgroundColour(colorArray[self.b_12Count])
        self.increase(self.b_12Count)
    
    def b13Click(self, event):
        self.button_13.SetBackgroundColour(colorArray[self.b_13Count])
        self.increase(self.b_13Count)
    
    def b14Click(self, event):
        self.button_14.SetBackgroundColour(colorArray[self.b_14Count])
        self.increase(self.b_14Count)
    
    def b15Click(self, event):
        self.button_15.SetBackgroundColour(colorArray[self.b_15Count])
        self.increase(self.b_15Count)
    
    def b16Click(self, event):
        self.button_16.SetBackgroundColour(colorArray[self.b_16Count])
        self.increase(self.b_16Count)
    
    def b17Click(self, event):
        self.button_17.SetBackgroundColour(colorArray[self.b_17Count])
        self.increase(self.b_16Count)
    
    def b18Click(self, event):
        self.button_18.SetBackgroundColour(colorArray[self.b_18Count])
        self.increase(self.b_18Count)
    
    def b19Click(self, event):
        self.button_19.SetBackgroundColour(colorArray[self.b_19Count])
        self.increase(self.b_19Count)
    
    def b20Click(self, event):
        self.button_20.SetBackgroundColour(colorArray[self.b_20Count])
        self.increase(self.b_20Count)
        
    def b21Click(self, event):
        self.button_21.SetBackgroundColour(colorArray[self.b_21Count])
        self.increase(self.b_21Count)
        
    def b22Click(self, event):
        self.button_22.SetBackgroundColour(colorArray[self.b_22Count])
        self.increase(self.b_22Count)
    
    def b23Click(self, event):
        self.button_23.SetBackgroundColour(colorArray[self.b_23Count])
        self.increase(self.b_23Count)
    
    def b24Click(self, event):
        self.button_24.SetBackgroundColour(colorArray[self.b_24Count])
        self.increase(self.b_24Count)
    
    def b25Click(self, event):
        self.button_25.SetBackgroundColour(colorArray[self.b_25Count])
        self.increase(self.b_25Count)
    
    def b26Click(self, event):
        self.button_26.SetBackgroundColour(colorArray[self.b_26Count])
        self.increase(self.b_26Count)
        
    def b27Click(self, event):
        self.button_27.SetBackgroundColour(colorArray[self.b_27Count])
        self.increase(self.b_27Count)
    
    def b28Click(self, event):
        self.button_28.SetBackgroundColour(colorArray[self.b_28Count])
        self.increase(self.b_28Count)
    
    def b29Click(self, event):
        self.button_29.SetBackgroundColour(colorArray[self.b_29Count])
        self.increase(self.b_29Count)
    
    def b30Click(self, event):
        self.button_30.SetBackgroundColour(colorArray[self.b_30Count])
        self.increase(self.b_30Count)
    
    def b31Click(self, event):
        self.button_31.SetBackgroundColour(colorArray[self.b_31Count])
        self.increase(self.b_31Count)
        
    def b32Click(self, event):
        self.button_32.SetBackgroundColour(colorArray[self.b_32Count])
        self.increase(self.b_32Count)
        
    def b33Click(self, event):
        self.button_33.SetBackgroundColour(colorArray[self.b_33Count])
        self.increase(self.b_33Count)
    

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle("frame_3")
        #self.button_15.SetBackgroundColour('RED')
        #self.button_16.SetBackgroundColour('BLACK')
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(8, 6, 0, 0)
        grid_sizer_2.Add(self.label_16, 0, 0, 0)
        grid_sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_2, 0, 0, 0)
        grid_sizer_2.Add(self.label_3, 0, 0, 0)
        grid_sizer_2.Add(self.button_30, 0, 0, 0)
        grid_sizer_2.Add(self.button_31, 0, 0, 0)
        grid_sizer_2.Add(self.button_32, 0, 0, 0)
        grid_sizer_2.Add(self.button_33, 0, 0, 0)
        grid_sizer_2.Add(self.label_4, 0, 0, 0)
        grid_sizer_2.Add(self.label_5, 0, 0, 0)
        grid_sizer_2.Add(self.button_26, 0, 0, 0)
        grid_sizer_2.Add(self.button_27, 0, 0, 0)
        grid_sizer_2.Add(self.button_28, 0, 0, 0)
        grid_sizer_2.Add(self.button_29, 0, 0, 0)
        grid_sizer_2.Add(self.label_6, 0, 0, 0)
        grid_sizer_2.Add(self.label_7, 0, 0, 0)
        grid_sizer_2.Add(self.button_22, 0, 0, 0)
        grid_sizer_2.Add(self.button_23, 0, 0, 0)
        grid_sizer_2.Add(self.button_24, 0, 0, 0)
        grid_sizer_2.Add(self.button_25, 0, 0, 0)
        grid_sizer_2.Add(self.label_8, 0, 0, 0)
        grid_sizer_2.Add(self.label_9, 0, 0, 0)
        grid_sizer_2.Add(self.button_18, 0, 0, 0)
        grid_sizer_2.Add(self.button_19, 0, 0, 0)
        grid_sizer_2.Add(self.button_20, 0, 0, 0)
        grid_sizer_2.Add(self.button_21, 0, 0, 0)
        grid_sizer_2.Add(self.label_10, 0, 0, 0)
        grid_sizer_2.Add(self.label_11, 0, 0, 0)
        grid_sizer_2.Add(self.button_14, 0, 0, 0)
        grid_sizer_2.Add(self.button_15, 0, 0, 0)
        grid_sizer_2.Add(self.button_16, 0, 0, 0)
        grid_sizer_2.Add(self.button_17, 0, 0, 0)
        grid_sizer_2.Add(self.label_12, 0, 0, 0)
        grid_sizer_2.Add(self.label_13, 0, 0, 0)
        grid_sizer_2.Add(self.button_10, 0, 0, 0)
        grid_sizer_2.Add(self.button_11, 0, 0, 0)
        grid_sizer_2.Add(self.button_12, 0, 0, 0)
        grid_sizer_2.Add(self.button_13, 0, 0, 0)
        grid_sizer_2.Add(self.label_14, 0, 0, 0)
        grid_sizer_2.Add(self.label_15, 0, 0, 0)
        grid_sizer_2.Add(self.label_17, 0, 0, 0)
        grid_sizer_2.Add(self.panel_4, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_5, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_6, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_1, 0, 0, 0)
        grid_sizer_2.Add(self.button_9, 0, 0, 0)
        sizer_3.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade
        
        #Events
        #EVT_BUTTON(self,-1,self.)

# end of class MyFrame2


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = MyFrame2(None, -1, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
