#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Sep 03 16:18:13 2009
#from wx._core import EVT_BUTTON
from main.mastermind import Mastermind
from main.color import Color
from main.row import Row
from wxPython._misc import wxMessageBox
from wxPython._core import wxOK

import wx

# begin wxGlade: extracode
# end wxGlade

colorArray = ['', 'BLACK', 'GREEN', 'BROWN', 'PURPLE', 'RED', 'WHITE', 'BLUE', 'YELLOW', 'BLACK' ]

ID_B9 = 9
ID_B10 = 10
ID_B11 = 11
ID_B12 = 12
ID_B13 = 13
ID_B14 = 14
ID_B15 = 15
ID_B16 = 16
ID_B17 = 17
ID_B18 = 18
ID_B19 = 19
ID_B20 = 20
ID_B21 = 21
ID_B22 = 22
ID_B23 = 23
ID_B24 = 24
ID_B25 = 25
ID_B26 = 26
ID_B27 = 27
ID_B28 = 28
ID_B29 = 29
ID_B30 = 30
ID_B31 = 31
ID_B32 = 32
ID_B33 = 33



class MyFrame2(wx.Frame):
    
    countDict = {9:0, 10:0, 11:0, 12:0, 13:0, 14:0, 15:0, 16:0, 17:0, 18:0, 19:0, 20:0, 21:0, 22:0, 23:0, 24:0, 25:0, 26:0, 27:0, 28:0, 29:0, 30:0, 31:0, 32:0, 33:0}
    buttonMap = {0:[10, 11, 12, 13], 1:[14, 15, 16, 17], 2:[18, 19, 20, 21], 3:[22, 23, 24, 25], 4:[26, 27, 28, 29], 5:[30, 31, 32, 33]}
    labelMap = {0:(14,15),1:(12,13),2:(10,11),3:(8,9),4:(6,7),5:(4,5)}
    rowCount = 0 
    colorList = []
    master = None
       
    def increase(self, buttonNo):
        if self.countDict[buttonNo] == 8:
            self.countDict[buttonNo] = 1
        else:
            self.countDict[buttonNo] = self.countDict[buttonNo] + 1
    
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        #Panels
        self.panel_1 = wx.Panel(self, -1)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_3 = wx.Panel(self, -1)
        self.panel_4 = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self, -1)
        self.panel_6 = wx.Panel(self, -1)
        
        #Labels
        self.label_2 = wx.StaticText(self, -1, "Hvítur")
        self.label_3 = wx.StaticText(self, -1, "Svartur")
        #self.label_1 = wx.StaticText(self, -1, "label_1")

        # Hvítt og svart hint fyrir player
        # röð 6
        self.label_4 = wx.StaticText(self, -1, " ") # hvítt hint
        self.label_5 = wx.StaticText(self, -1, " ") # svart hint
        # röð 5
        self.label_6 = wx.StaticText(self, -1, " ") # hvítt hint
        self.label_7 = wx.StaticText(self, -1, " ") # svart hint
        # röð 4
        self.label_8 = wx.StaticText(self, -1, " ") # hvítt hint
        self.label_9 = wx.StaticText(self, -1, " ") # svart hint
        # röð 3
        self.label_10 = wx.StaticText(self, -1, " ") # hvítt hint
        self.label_11 = wx.StaticText(self, -1, " ") # svart hint
        # röð 2
        self.label_12 = wx.StaticText(self, -1, " ") # hvítt hint
        self.label_13 = wx.StaticText(self, -1, " ") # svart hint
        # röð 1
        self.label_14 = wx.StaticText(self, -1, " ") # hvítt hint
        self.label_15 = wx.StaticText(self, -1, " ") # svart hint
        
        
        self.label_16 = wx.StaticText(self, -1, " ") # label_16: uppfæra þegar leikur klárast. Birta liti forrits.
        self.label_17 = wx.StaticText(self, -1, " ") # label_17
        
        #Buttons
        self.button_9 = wx.Button(self, ID_B9, "Leika")
        self.button_10 = wx.Button(self, ID_B10, "")
        self.button_11 = wx.Button(self, ID_B11, "")
        self.button_12 = wx.Button(self, ID_B12, "")
        self.button_13 = wx.Button(self, ID_B13, "")
        self.button_14 = wx.Button(self, ID_B14, "14")
        self.button_15 = wx.Button(self, ID_B15, "15")
        self.button_16 = wx.Button(self, ID_B16, "16")        
        self.button_17 = wx.Button(self, ID_B17, "17")
        self.button_18 = wx.Button(self, ID_B18, "18")
        self.button_19 = wx.Button(self, ID_B19, "19")
        self.button_20 = wx.Button(self, ID_B20, "20")       
        self.button_21 = wx.Button(self, ID_B21, "21")
        self.button_22 = wx.Button(self, ID_B22, "22")
        self.button_23 = wx.Button(self, ID_B23, "23")
        self.button_24 = wx.Button(self, ID_B24, "24")       
        self.button_25 = wx.Button(self, ID_B25, "25")
        self.button_26 = wx.Button(self, ID_B26, "26")       
        self.button_27 = wx.Button(self, ID_B27, "27")
        self.button_28 = wx.Button(self, ID_B28, "28")       
        self.button_29 = wx.Button(self, ID_B29, "29")
        self.button_30 = wx.Button(self, ID_B30, "30")
        self.button_31 = wx.Button(self, ID_B31, "31")
        self.button_32 = wx.Button(self, ID_B32, "32")
        self.button_33 = wx.Button(self, ID_B33, "33")
        
        # Button Binder
        self.Bind(wx.EVT_BUTTON, self.b9Click, id=ID_B9)
        self.Bind(wx.EVT_BUTTON, self.b10Click, id=ID_B10) 
        self.Bind(wx.EVT_BUTTON, self.b11Click, id=ID_B11) 
        self.Bind(wx.EVT_BUTTON, self.b12Click, id=ID_B12) 
        self.Bind(wx.EVT_BUTTON, self.b13Click, id=ID_B13) 
        self.Bind(wx.EVT_BUTTON, self.b14Click, id=ID_B14) 
        self.Bind(wx.EVT_BUTTON, self.b15Click, id=ID_B15) 
        self.Bind(wx.EVT_BUTTON, self.b16Click, id=ID_B16) 
        self.Bind(wx.EVT_BUTTON, self.b17Click, id=ID_B17) 
        self.Bind(wx.EVT_BUTTON, self.b18Click, id=ID_B18) 
        self.Bind(wx.EVT_BUTTON, self.b19Click, id=ID_B19) 
        self.Bind(wx.EVT_BUTTON, self.b20Click, id=ID_B20) 
        self.Bind(wx.EVT_BUTTON, self.b21Click, id=ID_B21) 
        self.Bind(wx.EVT_BUTTON, self.b22Click, id=ID_B22) 
        self.Bind(wx.EVT_BUTTON, self.b23Click, id=ID_B23) 
        self.Bind(wx.EVT_BUTTON, self.b24Click, id=ID_B24) 
        self.Bind(wx.EVT_BUTTON, self.b25Click, id=ID_B25) 
        self.Bind(wx.EVT_BUTTON, self.b26Click, id=ID_B26) 
        self.Bind(wx.EVT_BUTTON, self.b27Click, id=ID_B27) 
        self.Bind(wx.EVT_BUTTON, self.b28Click, id=ID_B28) 
        self.Bind(wx.EVT_BUTTON, self.b29Click, id=ID_B29) 
        self.Bind(wx.EVT_BUTTON, self.b30Click, id=ID_B30) 
        self.Bind(wx.EVT_BUTTON, self.b31Click, id=ID_B31) 
        self.Bind(wx.EVT_BUTTON, self.b32Click, id=ID_B32) 
        self.Bind(wx.EVT_BUTTON, self.b33Click, id=ID_B33)
        self.Bind(wx.EVT_BUTTON, self.onFinish, id=wxOK) 
 

        self.__set_properties()
        self.__do_layout()
        
        self.colorList = self.makeColors()
        self.master = Mastermind(self.colorList, 6, 4)
        # end wxGlade
        
    def getPlayerGuess(self):
        
        print "get player guess"
        count = self.rowCount
        print "count: ", count
        guessRow = []
        print "Button colors"
        buttonRow = self.buttonMap[count]
        for button in buttonRow:
            if colorArray[self.countDict[button]] == "":
                print "Vantar lit á takka"
                return []
            else:
                print colorArray[self.countDict[button]]
                guessRow.append(Color(colorArray[self.countDict[button]]))
        self.rowCount = self.rowCount + 1
        print "Skilar guessRow"
        return guessRow

        #guessRow = [Color('WHITE'), Color('BLUE'), Color('BLACK'), Color('YELLOW')]
   
    def setHintLabels(self):
        row = self.master.rows[self.rowCount-1]
        if self.rowCount-1 == 0:
            self.label_14.SetLabel(str(row.hintWhite))
            self.label_15.SetLabel(str(row.hintBlack))

        print "Fjöldi Hvítra : " + str(row.hintWhite)
        print "Fjöldi Svartra : " + str(row.hintBlack)
         
        
    def makeColors(self):
        black = Color("BLACK")
        green = Color("GREEN")
        brown = Color("BROWN")
        purple = Color("PURPLE")
        red = Color("RED")
        white = Color("WHITE")
        blue = Color("BLUE")
        yellow = Color("YELLOW")
        colorList = [black, green, brown, purple, red, white, blue, yellow] 
        return colorList
        
    def b9Click(self, event):
        won, lost = False, False
        guess = self.getPlayerGuess()
        if len(guess) != 0:
            won, lost = self.master.gradePlayerChoice(guess)
            self.setHintLabels()
            print "won lost"
            print won
        if won == True:
            dlgWon = wxMessageBox("Þú Vannst", "Til Hamingju", wxOK)
            self.onFinish()
        if lost == True:
            dlgLost = wxMessageBox("Þú tapaðir", "Því miður", wxOK)
            self.onFinish()

            #dlg.ShowModal()
            #self.label_1.SetLabel("Þú Vannst")
            #litur = self.button_10.BackgroundColour
            #strLitur = wx.TheColourDatabase.FindName(litur)
    
    def b10Click(self, event):
        self.button_10.SetBackgroundColour(colorArray[self.countDict[10] + 1])
        self.increase(10)
        
    def b11Click(self, event):
        self.button_11.SetBackgroundColour(colorArray[self.countDict[11] + 1])
        self.increase(11)
        
    def b12Click(self, event):
        self.button_12.SetBackgroundColour(colorArray[self.countDict[12] + 1])
        self.increase(12)
    
    def b13Click(self, event):
        self.button_13.SetBackgroundColour(colorArray[self.countDict[13] + 1])
        self.increase(13)
    
    def b14Click(self, event):
        self.button_14.SetBackgroundColour(colorArray[self.countDict[14] + 1])
        self.increase(14)
    
    def b15Click(self, event):
        self.button_15.SetBackgroundColour(colorArray[self.countDict[15] + 1])
        self.increase(15)
    
    def b16Click(self, event):
        self.button_16.SetBackgroundColour(colorArray[self.countDict[16] + 1])
        self.increase(16)
    
    def b17Click(self, event):
        self.button_17.SetBackgroundColour(colorArray[self.countDict[17] + 1])
        self.increase(17)
    
    def b18Click(self, event):
        self.button_18.SetBackgroundColour(colorArray[self.countDict[18] + 1])
        self.increase(18)
    
    def b19Click(self, event):
        self.button_19.SetBackgroundColour(colorArray[self.countDict[19] + 1])
        self.increase(19)
    
    def b20Click(self, event):
        self.button_20.SetBackgroundColour(colorArray[self.countDict[20] + 1])
        self.increase(20)
        
    def b21Click(self, event):
        self.button_21.SetBackgroundColour(colorArray[self.countDict[21] + 1])
        self.increase(21)
        
    def b22Click(self, event):
        self.button_22.SetBackgroundColour(colorArray[self.countDict[22] + 1])
        self.increase(22)
    
    def b23Click(self, event):
        self.button_23.SetBackgroundColour(colorArray[self.countDict[23] + 1])
        self.increase(23)
    
    def b24Click(self, event):
        self.button_24.SetBackgroundColour(colorArray[self.countDict[24] + 1])
        self.increase(24)
    
    def b25Click(self, event):
        self.button_25.SetBackgroundColour(colorArray[self.countDict[25] + 1])
        self.increase(25)
    
    def b26Click(self, event):
        self.button_26.SetBackgroundColour(colorArray[self.countDict[26] + 1])
        self.increase(26)
        
    def b27Click(self, event):
        self.button_27.SetBackgroundColour(colorArray[self.countDict[27] + 1])
        self.increase(27)
    
    def b28Click(self, event):
        self.button_28.SetBackgroundColour(colorArray[self.countDict[28] + 1])
        self.increase(28)
    
    def b29Click(self, event):
        self.button_29.SetBackgroundColour(colorArray[self.countDict[29] + 1])
        self.increase(29)
    
    def b30Click(self, event):
        self.button_30.SetBackgroundColour(colorArray[self.countDict[30] + 1])
        self.increase(30)
    
    def b31Click(self, event):
        self.button_31.SetBackgroundColour(colorArray[self.countDict[31] + 1])
        self.increase(31)
        
    def b32Click(self, event):
        self.button_32.SetBackgroundColour(colorArray[self.countDict[32] + 1])
        self.increase(32)
        
    def b33Click(self, event):
        self.button_33.SetBackgroundColour(colorArray[self.countDict[33] + 1])
        self.increase(33)
    
    def onFinish(self):
        self.Close(True)

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle("RuMastermind")
        #self.button_15.SetBackgroundColour('RED')
        #self.button_16.SetBackgroundColour('BLACK')
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(8, 6, 0, 0)
        grid_sizer_2.Add(self.label_16, 0, 0, 0)
        grid_sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_2, 0, 0, 0)
        grid_sizer_2.Add(self.label_3, 0, 0, 0)
        grid_sizer_2.Add(self.button_30, 0, 0, 0)
        grid_sizer_2.Add(self.button_31, 0, 0, 0)
        grid_sizer_2.Add(self.button_32, 0, 0, 0)
        grid_sizer_2.Add(self.button_33, 0, 0, 0)
        grid_sizer_2.Add(self.label_4, 0, 0, 0)
        grid_sizer_2.Add(self.label_5, 0, 0, 0)
        grid_sizer_2.Add(self.button_26, 0, 0, 0)
        grid_sizer_2.Add(self.button_27, 0, 0, 0)
        grid_sizer_2.Add(self.button_28, 0, 0, 0)
        grid_sizer_2.Add(self.button_29, 0, 0, 0)
        grid_sizer_2.Add(self.label_6, 0, 0, 0)
        grid_sizer_2.Add(self.label_7, 0, 0, 0)
        grid_sizer_2.Add(self.button_22, 0, 0, 0)
        grid_sizer_2.Add(self.button_23, 0, 0, 0)
        grid_sizer_2.Add(self.button_24, 0, 0, 0)
        grid_sizer_2.Add(self.button_25, 0, 0, 0)
        grid_sizer_2.Add(self.label_8, 0, 0, 0)
        grid_sizer_2.Add(self.label_9, 0, 0, 0)
        grid_sizer_2.Add(self.button_18, 0, 0, 0)
        grid_sizer_2.Add(self.button_19, 0, 0, 0)
        grid_sizer_2.Add(self.button_20, 0, 0, 0)
        grid_sizer_2.Add(self.button_21, 0, 0, 0)
        grid_sizer_2.Add(self.label_10, 0, 0, 0)
        grid_sizer_2.Add(self.label_11, 0, 0, 0)
        grid_sizer_2.Add(self.button_14, 0, 0, 0)
        grid_sizer_2.Add(self.button_15, 0, 0, 0)
        grid_sizer_2.Add(self.button_16, 0, 0, 0)
        grid_sizer_2.Add(self.button_17, 0, 0, 0)
        grid_sizer_2.Add(self.label_12, 0, 0, 0)
        grid_sizer_2.Add(self.label_13, 0, 0, 0)
        grid_sizer_2.Add(self.button_10, 0, 0, 0)
        grid_sizer_2.Add(self.button_11, 0, 0, 0)
        grid_sizer_2.Add(self.button_12, 0, 0, 0)
        grid_sizer_2.Add(self.button_13, 0, 0, 0)
        grid_sizer_2.Add(self.label_14, 0, 0, 0)
        grid_sizer_2.Add(self.label_15, 0, 0, 0)
        grid_sizer_2.Add(self.label_17, 0, 0, 0)
        grid_sizer_2.Add(self.panel_4, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_5, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_6, 1, wx.EXPAND, 0)
        #grid_sizer_2.Add(self.label_1, 0, 0, 0)
        grid_sizer_2.Add(self.button_9, 0, 0, 0)
        sizer_3.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade
        
        #Events
        #EVT_BUTTON(self,-1,self.)

# end of class MyFrame2


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = MyFrame2(None, -1, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
