#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Tue Sep 01 00:40:31 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame9(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame9.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_2 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.button_7 = wx.Button(self.window_2_pane_1, -1, "Viltu sjá eitthvað ógeð")
        self.bitmap_5 = wx.StaticBitmap(self.window_2_pane_2, -1, wx.Bitmap("C:\\Documents and Settings\\omartr\\My Documents\\My Pictures\\Mynd.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_5.Hide()

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        # events
        
        self.Bind(wx.EVT_BUTTON, self.OnClicked)

    def __set_properties(self):
        # begin wxGlade: MyFrame9.__set_properties
        self.SetTitle("frame_10")
        # end wxGlade
    
    def OnClicked(self,event):
        self.bitmap_5.Show()
        

    def __do_layout(self):
        # begin wxGlade: MyFrame9.__do_layout
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18.Add(self.button_7, 0, wx.ALL, 0)
        self.window_2_pane_1.SetSizer(sizer_18)
        sizer_20.Add(self.bitmap_5, 0, 0, 0)
        self.window_2_pane_2.SetSizer(sizer_20)
        self.window_2.SplitVertically(self.window_2_pane_1, self.window_2_pane_2)
        sizer_15.Add(self.window_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_15)
        sizer_15.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame9


class MyMenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyMenuBar.__init__
        wx.MenuBar.__init__(self, *args, **kwds)
        wxglade_tmp_menu = wx.Menu()
        self.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.Append(wxglade_tmp_menu, "Tools")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyMenuBar.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyMenuBar.__do_layout
        pass
        # end wxGlade

# end of class MyMenuBar


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_10 = MyFrame9(None, -1, "Halló þetta er hundur")
    app.SetTopWindow(frame_10)
    frame_10.Show()
    app.MainLoop()
